spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:postgresql://localhost:5432/university
    username: postgres
    password: postgres
    dialect: org.hibernate.dialect.PostgreSQL94Dialect

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate.jdbc.batch_size: 20
      hibernate.cache.use_query_cache: false
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_structured_entries: false
      hibernate.cache.use_minimal_puts: false